### ISSUE TITLE
~~ on range-URN for ordered collection?

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/citeobj#33]
In OHCO2, something like this works:

`corpus ~~ CtsUrn("urn:cts:greekLit:tlg0012.tlg001.msA:1.1-1.10")`

I don't *think* this is currently implemented:

`citeRepository.collectionData ~~ Cite2Urn("urn:cite2:hmt:msA.v1:1r-2v")`

…which could yield a citeRepository whose collectionData contains four Objects.

Since we have `indexOf` and citableObject it would not be hard to do this client-side. But this might prove convenient in the service.

(My apologies if this is already in place, and I missed it on my first evening's reading of the API.)

**Comment by neelsmith** [comment]
good idea.  will implement this.

**Comment by neelsmith** [comment]
done
