### ISSUE TITLE
CitePropertyValue could use fields for PropertyType and label

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/citeobj#39]
With that, once you have a CiteObject, you would have everything you need to display it and work with it. Without propertyType and label, you have to go *back* to the Collection, drill down to the CitePropertyDef, filter for the right one, and extract Label and Type values.

(I don't think the Vocabulary is as important for consumption of CiteObjects).

**Comment by neelsmith** [comment]
For 2.0, adding a CitePropertyImplementation in addition to property *value* and property *defintion*.  This should clarify things.

**Comment by neelsmith** [comment]
done.
