### ISSUE TITLE
Need to add resolver to build.sbt

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/citeobj#55]
`resolvers += Resolver.bintrayRepo("neelsmith", "maven"),`

citeObj relies on orca, which relies on ohco2 (5.0.0).

**Comment by neelsmith** [comment]
Investigating this.  I think the citeObj dependency needs to be updated, and we may be good to go.

**Comment by neelsmith** [comment]
For now at least, adding it to build.sbt.   Closing this, but filing a non-bug issue to explore this later.
