### ISSUE TITLE
Apropos #56, Labels should be in the list of properties

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/citeobj#57]
We used to treat labels as just another property. I think we need to here. For searching, for example, a String search on the whole collection should include labels, and since we are allowed to search on specific properties, the label needs to be one of them.

**Comment by neelsmith** [comment]
No.  URN and Label are inherent to all citable objects.  We should enable searching on labels, but the data structure here is right: search is implemented wong.  Closing this, leaving #56 as a bug.
