### ISSUE TITLE
String search, limited by property URN, does not work

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/citeobj#58]
`myRepository.stringContains(Cite2Urn("urn:cite2:hmt:msA.v1.siglum:"),"msA", true)` throws this error:

~~~
java.lang.IllegalArgumentException: requirement failed: Exception: found 0 match(es) for urn:cite2:hmt:msA.v1.siglum:
~~~

(This particular combination of parameters does not seem to be in the tests ;-)

**Comment by Eumaeus** [comment]
Seems to be the case for numeric searches, too.

**Comment by neelsmith** [comment]
fixed
