### ISSUE TITLE
urnMatch fails…

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/citeobj#59]
when a collection has both CtsUrn and Cite2Urn properties. 

Look in CiteObject.scala, around line 305. I think it makes a vector of *all* URN properties, and tries to twiddle CTS ~~ Cite2, throwing an error.

**Comment by neelsmith** [comment]
Note: the error is in function `def urnMatch(u: Urn): Boolean`

The previous comment correctly identifies th bug.

**Comment by neelsmith** [comment]
resolved in 3.1.3
